### ISSUE TITLE
Merge Pay Summary Status and cut-off into Just Status

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#1]
- Garrick, I know you discussed why you kept Cut-off as a separate status. However, I’ve been finding that it’s a little difficult to follow.
- can we move to the single status that includes cut-off, as indicated in Adam’s documentation
- In Adam’s document for Payroll Status, did you implement PendingApproval, I can not get to that state.  This is fine, I believe it can be removed.
 
- Status State of Pay Period Summary should flow as follows
 ![PaySumaryState](https://user-images.githubusercontent.com/10456426/114240331-93b6f900-9944-11eb-8b8e-6692d8e961ed.png)

**Comment by GarrickConvverge** [comment]
I have updated the Power App to only use one status for pay period summaries, I have left the cut off column on both the pay entry screen and pay summary screen to give an indication to the user why they might not be able to modify entries and only approve.

I have also made the assumption that you can click to re-open after a pay period summary has been approved but not exported. (The state machine indicates this can only happen at the Cut-off Status, it's a pretty quick change either way)
