### ISSUE TITLE
Integration does not respect Cut-off rule

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#10]
When a job is integrated and a district Pay Period Summary is Cutoff, Approved, or closed - All entries for that job should be moved to the next pay period.  

Currently, they end up in the cut-off period.

**Comment by vikmol** [comment]
Real time sync to SQL of PayPeriodSummary Status change in SP is working now (as of Apr 16th).
I am keeping it open trying to replace there a Premium connector with a custom one.
