### ISSUE TITLE
In Pay Entry, Add Filter for Ticket #

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#14]
The most common way to review entries on this page is by ticket number, in a pay period there can be many tickets.  In the grid it can be difficult to identify all the entries for a specific ticket.  Especially now, when there are so many more entries for a ticket than in the current system.

Adding a search box for Ticket # will help.

There is room if er condenses some of the other drop-downs.
![image](https://user-images.githubusercontent.com/10456426/115264581-a7f0b800-a0f3-11eb-81f1-a0c83b1a84af.png)

**Comment by cgaine** [comment]
Can you sort the values numerically in the drop-down?

**Comment by GarrickConvverge** [comment]
Are ticket numbers always numerical?

**Comment by cgaine** [comment]
Yes ticket number is always numerical.

**Comment by GarrickConvverge** [comment]
I'll have to change the column so that it is numerical as opposed to a string in sharepoint

**Comment by cgaine** [comment]
Lets hold off on this.  There may be implications in the back end.

**Comment by cgaine** [comment]
Viktor made a good point.  Ticket numers are all 6 digits,  Can we sort alphabetically.  That should work

**Comment by GarrickConvverge** [comment]
Sounds good
