### ISSUE TITLE
Missing 'Driver 3' Pay Position

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#17]
We are missing the Driver 3 pay position that is used for B-Train and Chem van bonuses

Both Chem van, and B-Train pay types need to be associated with Driver 3 position only

**Comment by GarrickConvverge** [comment]
The logic for Driver 3 should be in the Power App for B-train and Chem Van

**Comment by cgaine** [comment]
HI Garrick. sorry for the misunderstanding. We don't need to introduce additional logic for filtering.  Chemvan and bTrain should work the same way as all the other pay Types.  No need to filter.  Just the calculation would apply to only Driver 3.. meaning the only position in the SP list with an entry should be for Driver 3.

If you have any questions give me a call.
