### ISSUE TITLE
View Statements shows all employees, not just employees for specific pay period Summary

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#20]
View Statements shows all employees for the Service Point and Pay period, not just employees for specific pay period Summary.

The total amount is filtered properly, but when you click on pay statements all Edmonton employees are listed (in this example)

![image](https://user-images.githubusercontent.com/10456426/116740067-b7081d80-a9b1-11eb-98d2-e0d125d6b306.png)

**Comment by GarrickConvverge** [comment]
I have added a Pay Period Summary Dropdown on the pay statement screen which will be set when you click the corresponding "View statements" button. This should allow you to filter the pay statement grid for a pay period based on the pay period summary on top of the service point. The dropdown selection is filtered based on service point and pay period.
