### ISSUE TITLE
Auto Refresh on Pay entries screen happening to often

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#21]
When there are lots of entries, the pages sometimes unusable, it kinda seems like the auto-refresh happens the next time as soon as the first one is done.  If we have an auto refresh it should be on a lot larger interval.

Maybe its better to have a manual refresh on the entries page?  Instead of auto-refresh.

**Comment by GarrickConvverge** [comment]
Yeah I can add a manual refresh, how many records do you expect to see in a pay period?

**Comment by cgaine** [comment]
This is the most pay entries we had for one pay period this year.  However, keep in mind that in the old system, 1 entry could represent base variable pay, Standy, and Crew efficiency.

![image](https://user-images.githubusercontent.com/10456426/117212798-07b7b600-adb8-11eb-8c28-733e06370314.png)

**Comment by cgaine** [comment]
Did you remove the auto refresh?

**Comment by GarrickConvverge** [comment]
I have removed the auto refresh

**Comment by GarrickConvverge** [comment]
There is now a button on the top right that can be used to manually refresh data
