### ISSUE TITLE
Default Position to Employees Position when adding entry

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#22]
When adding manual entries, DAs are not always familiar with an employee's specific position.  Can we have the App default the Position field to the Employees position?  They may need to change it based on the job the employee performed, but defaulting the value would handle most cases.

**Comment by GarrickConvverge** [comment]
For this, I have noticed that there is a position field in the Common_Employee table, but not all positions line up with the application, is there a mapping between this column and pay position, alternatively we could add a PayPositionId and PayPositionName Column to the Common_Employee Table and do the mapping there, if need be.

**Comment by cgaine** [comment]
for positions that receive variable compensation, they line up.  Many employees do not receive variable compensation.  If an employee is pocked that does not line up then leave blank.
