### ISSUE TITLE
On Pay Entry Screen, Make Find Ticket# filter also Search OVPP

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#23]
On Pay Entry Screen, Make Find Ticket# filter also Search the OVPP# field.  If a value matches either column show the entries

**Comment by cgaine** [comment]
Can no longer type into the drop-down.  The way the drop-down worked before worked a lot better.  Where there are a lot of tickets we don't want to hunt through a list, they need to be able to type.  Dont need to show what type the number is.

**Comment by GarrickConvverge** [comment]
Sorry about that sometimes changing settings with a combo box in power apps resets the search flag, I'll reset it.
