### ISSUE TITLE
Print failed - One instance

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#24]
Most prints succeed, however the print during the training session failed.  Is there a buga causing certain print scenarios to fail?

![image](https://user-images.githubusercontent.com/10456426/116890929-61b75080-abeb-11eb-90b1-445e99660333.png)

**Comment by GarrickConvverge** [comment]
Hey Chris, would you be able to navigate into the flow that failed and share the error with me, I am unable to access the Production Flow. The alternative would be to share the prod flow with me.

**Comment by cgaine** [comment]
The error was in the test environment
*https://canada.flow.microsoft.com/manage/environments/3fc401ae-d0cd-4025-b4c8-221775fc58e7/flows/shared/f56ff5f3-ab7f-4e57-9a1e-8affade63b43/runs**

On Apr 30th at 10:33am

**Comment by GarrickConvverge** [comment]
Hi Chris, It looks like a user was missing Matthew Flatla (31321: id), maybe we can add a failure catch and continue the process with uploading the remaining statements but include the users it failed on in the email if it does happen.

**Comment by GarrickConvverge** [comment]
To clarify the user was missing from the Common list

**Comment by cgaine** [comment]
Yes lets continue with processing all the others.  The can we email at the end indicating to the users that there was an error and not all statements printed?

**Comment by GarrickConvverge** [comment]
Printing statements should now continue on failure, and state which users failed print
