### ISSUE TITLE
Add Deleted Flag to Pay Entries

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#27]
Its been difficult to sync entries when deleted.  Also to track it an entry has been deleted.  

Can you implement a deleted flag and instead of deleting Pay entries, just set the Deleted flag to true.  In the App you should not show any deleted entries in any part of the app...,printouts, Totals,  and such, should not include the value of deleted entries.

**Comment by cgaine** [comment]
can you ensure the printout and export reflect the deleted status of a pay entry

**Comment by GarrickConvverge** [comment]
A note on this one when importing records ensure the IsDeleted field is set to 0, this is a numeric field to reduce warning on filters in Power Apps, when an item is deleted this can be set to 1.

**Comment by GarrickConvverge** [comment]
The soft deleted entries should now also be ignored by the reports

**Comment by vikmol** [comment]
Confirmed - Statement print out ignores deleted pay entries now. I still have not tested Export function.
API has been updated in Test to set IsDeleted to 0 for SQL to SP pay entries push.

**Comment by vikmol** [comment]
IsDeleted property was added to the VP_PayEntry list in Prod with a default setting to zero.
As well, sync API was updated to accommodate that property for managing deleted (marked as deleted) in SP records during SP to SQL sync.
