### ISSUE TITLE
Rounding error in totals

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#30]
Take a look at this statement.  The values of each ticket add up to 2,107.97.  However, the total adds up to 2,107.99

![image](https://user-images.githubusercontent.com/10456426/119736997-d58bf800-be3b-11eb-9e2c-d18b4b1579e1.png)

**Comment by GarrickConvverge** [comment]
HI Chris for this would you want the values to be rounded to the nearest cent when calculated? both the app and the import appear to have decimal cents.

**Comment by cgaine** [comment]
Yes please round the amount to the nearest cent, we will also update the integration to round the values
Thanks,

**Comment by GarrickConvverge** [comment]
I have updated the logic to round to the nearest cent when editing or adding entries
