### ISSUE TITLE
Remove B-Train minimum

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#31]
The minimum KM of 300 applies to the day, and not a trip.  There are some days a driver will perform multiple trips, each needs to be recorded as a separate haul in the system (ie different customer, truck, product etc.) 
Example:
2 hauls in one day
A: 200 km
B 150 km
Driver should be paid 350 km in bonus, not 600

**Comment by GarrickConvverge** [comment]
would there need to be additional logic based on days? Also for chem van is the minimum distance also daily?

**Comment by cgaine** [comment]
What are your thoughts? Is there a basic way to validate the daily amount across multiple entries?

**Comment by cgaine** [comment]
Yes it applies to Chem-Van also, and both B-Train and Chem-van contribute to the overall min KMs

**Comment by GarrickConvverge** [comment]
it will be quite complicated to get it to work using flow for validating the daily minimum also in how to display this on the pay statement/pay entries when multiple entries are below the threshold. Just removing the minimum is easy.

**Comment by cgaine** [comment]
Possibly even easier would be to change the minimum to something really
small.

**Comment by GarrickConvverge** [comment]
Yeah changing the minimum to 0 or a small number would also work

**Comment by cgaine** [comment]
Thanks, we'll try that for now
