### ISSUE TITLE
Spelling of FSJ on Manually created Pay Entries

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#32]
Requirement changed....

After discussion with Chris, I have created a new SharePoint list VP_Employees in App Reference.

It is, basically, a list with the almost the same structure as Common_Employees, but with a couple of distinctions:

1.	There are added two new properties – HomeServicePointId & HomeServicePointName that can be picked up directly from an employee record and no need of looking them up.
2.	The list is filtered to include only employees that are eligible for a Variable Pay. So, there is not any employee from Calgary* district.

If you switch the app source of employees to this list and adjust logic for HomeServicePoint handling it should resolve the issue we have with FSJ name.
As well, it should eliminate a potential user error with picking up an employee that is not eligible for VP.

Please review the change and let us know if it works for you.

**Comment by GarrickConvverge** [comment]
This list has been updated To VP_Employees and everything should be wired up to correctly approve and export FSJ
