### ISSUE TITLE
New Payment Type JCIB

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#35]
Pay Type Name: JCIB

Generally this pay type should be populated from integration, though may be corrections from the App.

Should be populated to a separate Pay Period Summary -NOTE: Viktor and I tested this and does not work.  These will need to go in the default Pay Period Summary.

Payroll export Information:

Position ID | Payment Type | Pay# | Description | Earnings Code | Earnings Amount
-- | -- | -- | -- | -- | --
N20S000001060 | CPA | 10 | JOBCNTIN | 71 | 1400

We need to change the data model to handle this export, as this new pay type has a different pay code

Add PayType to VP_PayrollExportMapping

Change payroll export mapping to use Pay type to get earning code

Remove PaySummaryType from  VP_PayrollExportMapping  -- After deploy to production

VP_PayrollExportMapping needs to be updated for each pay type

Pay Type is linked to PaySummary Type to use on Pay Summary screen

**Comment by awangatsanjel** [comment]
Testing Database is ready

**Comment by GarrickConvverge** [comment]
It looks like the VP_MonthlyJobCountIncentiveSchedule doesn't have any data in it, i am assuming this is the table to do the calculation from, also what is the calculation for this type?

**Comment by GarrickConvverge** [comment]
I don't see JOBCNTIN in the VP_PayrollExportMapping, I do have the Flow updated to deal with all situations in this list, I think all we need is here is:

- Update the PaySummaryTypeId of Monthly Job Count Incentive to 5
- Create a new Column in VP_PayrollExportMapping for JOBCNTIN with potentially the following values

Title: 8
SqlRow_Id: 8
PayrollDescription: JOBCNTIN
EarningCode: 71
ServiceLineId: 13
SerivceLineName: Primary Cementing
PaySummaryTypeid: 5
PaySummaryTypeName: Variable Pay

and then potentially a second entry for remedial as well?

**Comment by awangatsanjel** [comment]
Hi Garrick,

The structure of VP_PayrollExportMapping  has been changed. The ADP code maps to pay type now, not pay summary type any more. The new structure and data are in 'App Testing'. Viktor didn't make changes in 'App Reference' to avoid affecting current app functionality.

Please refer to Viktor's email sent on last Friday.

You may have to adjust the ADP export logic accordingly.

Job Count Incentive applies to both service line, so there is no value in service line fields. It is same as meal allowance. If it is easier to handle with service line value, we definitely can populate two rows for the service lines.

**Comment by GarrickConvverge** [comment]
Sounds good, would you also be able to update the VP_MonthlyJobCountIncentiveSchedule list with some data and the formula to calculate its cost?

**Comment by awangatsanjel** [comment]
VP_MonthlyJobCountIncentiveSchedule is in App Reference and data has been populated. It is a lookup table, the incentive amount are already pre-calculated by job count. e.g. Employee A has done 12 jobs in the month, just use 12 to look up the table to get the amount to pay.

**Comment by GarrickConvverge** [comment]
Perfect.

-  The export should now use PayTypeID from the AppTesting VP_PayrollExportMapping list to group pay entries
- In the case of Base Variable it will also group on Primary/Remedial
- PaySummaryTypeId will still be necessary for the totals on the pay summary screen only
- The logic for Monthly Job Count Incentive has been implemented, there just needs to be a record in the VP_MonthlyJobCountIncentiveSchedule List

One question I have is for the names for the Export Process 
From my understanding the name is structured as EPIN20S[Earnings Code].csv, my question is, is that 20 a constant number or is this also dynamic, for instance based on pay period number?

**Comment by cgaine** [comment]
EPIN20S is constant and does not change

**Comment by cgaine** [comment]
The only mandatory fields for Job count incentive bonus are Employee, Ticket#, Date, PayType and Quantity.

The Quantity will be used in the lookup to VP_MonthlyJobCountIncentiveSchedule against the JobCount Column.

**Comment by awangatsanjel** [comment]
[MonthlyJobCountIncentiveSchedule] has been corrected. The amount is for one job which is qualified for Monthly Job Count Incentive based its ordinal in the month for an employee.
