### ISSUE TITLE
Pay# in Export can not be hard coded

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#36]
A column for Pay Period number should be added to VP_PayPeriods, corresponding to the image below.

![image](https://user-images.githubusercontent.com/10456426/120365787-1c5e6f80-c2cc-11eb-8a1a-f57132b4c645.png)

This Pay period number needs to be used in the export file

**Comment by awangatsanjel** [comment]
Testing database is updated
