### ISSUE TITLE
Export should combine all selected pay period summaries

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#37]
Currently, the export creates separate export files for each selected Service Point.  In the end, Amy just has to combine these files together.  Can we email a single set of Export files for the selected Service Points.

In addition, each pay entry creates one row in the export file.  the Entries should be summed up per employee within each file.

**Comment by cgaine** [comment]
I updated this requirement to Sum pay entries per employee within each export file.

**Comment by cgaine** [comment]
When testing the export for Red Deer Jun13-26 PP I got 2 export files, Primary and Remedial, but I only entered to primary entries

![image](https://user-images.githubusercontent.com/10456426/123001669-37be1700-d36e-11eb-86a4-22c9375bf985.png)

**Comment by GarrickConvverge** [comment]
I will look into this

**Comment by GarrickConvverge** [comment]
It should be good now, it was just due to the conditional logic for base variable pay.
