### ISSUE TITLE
No way to close a Pay Period

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#39]
Automate the pay period close - when all pay period summaries

**Comment by vikmol** [comment]
I have created a SQL job to update Pay Period Status on PayPeriod table. The task runs overnight once per a day for now. It scans all PayPeriodSummary Statuses, aggregate them by PayPeriods, and set Status for each Pay Period to the minimal aggregated from PayPeriodSummary.
