### ISSUE TITLE
Missing "Sanjel" customer

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#4]
Sanjel is not in the list of customers
![image](https://user-images.githubusercontent.com/10456426/116742329-73fb7980-a9b4-11eb-9081-337076aa227f.png)

![image](https://user-images.githubusercontent.com/10456426/116742270-5f1ee600-a9b4-11eb-9478-5460b5369ecb.png)

**Comment by vikmol** [comment]
Added 'Sanjel Energy Services Inc.' customer.

**Comment by cgaine** [comment]
Garrick can you help troubleshoot why Sanjel Energy Services is not showing up?

**Comment by cgaine** [comment]
Now there are 3 of each client in the list
