### ISSUE TITLE
Clean up VP_PayType list structure

### ISSUE THREAD

**Issue by vikmol** [Sanjel-Energy-Services/VariablePay_WorkItems#40]
It seems the 'VP_PayType' list in SharePoint 'App Reference' has a legacy column 'PaySummaryType' that was replaced some time ago with a pair of columns  'PaySummaryTypeId' and  'PaySummaryTypeName', but was not deleted.
The 'PaySummaryType' column data is not maintained anymore and it needs to be deleted upon Garrick's confirmation that it is not used in the app.

**Comment by vikmol** [comment]
Garrick, could you please review usage of the 'PaySummaryType' column in the the 'VP_PayType' list and confirm if it can be deleted?

**Comment by GarrickConvverge** [comment]
I will look into it

**Comment by GarrickConvverge** [comment]
It should be safe

**Comment by vikmol** [comment]
The 'PaySummaryType' column has been deleted from the 'VP_PayType' list in 'App Reference'.
