### ISSUE TITLE
Aggregated amounts stored on PayEntry / PayPeriodSummary / PaySummary are inconsistent

### ISSUE THREAD

**Issue by vikmol** [Sanjel-Energy-Services/VariablePay_WorkItems#41]
In Prod, for completed pay period 05/02/2021 – 05/15/2021, there are some discrepancies / incompleteness with storing amounts for PayPeriodSummary and Pay Summary.

All entities there (PayEntry / PayPeriodSummary / PaySummary) have status 16. 
However, in some cases Amount property on corresponding PayPeriodSummary records (or TotalAmount on PaySummary) has zero value while associated pay entries exist with non-zero amounts. 
In some other cases those properties are populated.

The screenshot below illustrates that picture for Prod 05/02/2021 – 05/15/2021 period.
![image](https://user-images.githubusercontent.com/55720268/121241466-b5efc900-c858-11eb-9c52-ad2b61e479ed.png)

**Comment by vikmol** [comment]
An example of PayPeriodSummary data in SharePoint:
![image](https://user-images.githubusercontent.com/55720268/121241798-10892500-c859-11eb-893e-4e02177746f4.png)

**Comment by GarrickConvverge** [comment]
Yeah that's strange, looking into it

**Comment by GarrickConvverge** [comment]
I believe I know what caused this issue. 

When updating the states the approval button disable button logic was missed (pending used to be state 2, cut-off is now state 2), allowing managers to approve cut-off Pay period summaries before pay summaries were approved.

I have put an update that should block this from now on. 

Pay Period Summary Totals are calculated from the Pay Summary Totals, therefore they were not calculated on the pay summary approval process first.

I was able to track this back from the pay summary version history.

**Comment by cgaine** [comment]
Thanks Garrick, that makes sense
