### ISSUE TITLE
Steven Hinz Pay Summer will not go into Pending Status

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#43]
![image](https://user-images.githubusercontent.com/10456426/122987630-0ccbc700-d35e-11eb-88df-86dcbe2c7996.png)

Can not find a reason for Steven's pay summary not to go Pending status.  However, there are 3 deleted pay entries.  With this a new feature, is that preventing the status from changing?

**Comment by GarrickConvverge** [comment]
I will double check

**Comment by GarrickConvverge** [comment]
Hi Chris, that's exactly what it was, its been updated in dev
