### ISSUE TITLE
API exception when an Employee Id is missing 

### ISSUE THREAD

**Issue by vikmol** [Sanjel-Energy-Services/VariablePay_WorkItems#48]
When a new employee is on a job and his record is not in eService yet, his name is manually entered in eService instead of picking it up from drop-down .
In such case EmployeeId is not populated in eService data and it causes an exception during WorkAssignment to PayEntry processing. The exception terminates job data processing and employee records with correct data get skipped.

**Comment by cgaine** [comment]
We should handle this the same way we handle other exceptions.  Continue processing the remainder of the work assignments and notify the approving manager about the exception.  Including in the message details such as the employees name, job number and the reason for the exception.
