### ISSUE TITLE
Uncertainty with treating JobDate in the app (UTC vs Local DateTime)

### ISSUE THREAD

**Issue by vikmol** [Sanjel-Energy-Services/VariablePay_WorkItems#54]
Auto processed pay entries were pushed from SQL to SharePoint VP_PayEntries list having JobDate value set in a Local Time. 
It is not clear how it works with manual entries, but, it seems, it uses local times too to write JobDate property to the list.

Within the app, it seems, dates are displayed as UTC, though. 

So, in cases when JobDate time is after 6:00pm (in local time, I can see it going to the SP list directly in browser), pay entries in the app and on printouts are shown with the next day date (it is the next day already in UTC zone).

It is confusing and Job Dates might be shown not correct. We had a couple of cases when some pay entries were printed out with JobDate the next day after PayPeriod last day, 

On Oct 28 I changed logic for auto processing and started passing JobDate value to the VP_PayEntries as a Date instead of DateTime. I hope it should resolve the issue and, i believe, it did. Partially, at least.

Today, following up previous day changes, I noticed that manual entries might have the similar issue.

I.e. Pay Entries in VP_PayEntries with IDs 12188, 12189 were added manually and in the SP list the JobDate is shown as '10/24/2021 11:00pm' and '10/25/2021 11:00pm'. In the app the same records are shown with dates '10/25/2021' and '10/26/2021' accordingly.
The real job dates in local time are '10/25/2021' and '10/26/2021'.
I am not sure if it was users conscious date offset used during data entry or DateTime picked by user was silently converted to UTC by the app  /platform. 

We need to clarify how datetime values are handled in the app. Also, maybe, consider switching handling of entities' datetime properties (except system / log related ones) strictly as dates to avoid any confusion.

**Comment by GarrickConvverge** [comment]
Hi Chris, 

So what happens from SharePoint is the time is being converted to the sites regional time, When selecting the date in PowerApps it will try to insert the users current time and change it to the regional time in SharePoint eg:

If you are in MST and select 11/2/2021, it will insert 11/2/2021 12:00 AM (the back end will be UTC)
If you are in EST time and select 11/2/2021, it will insert 11/1/2021 10:00AM (also the back end will be UTC)

We could add the time zone offset power apps uses (in minutes) to the pay entry but you would need to do a calculation to correct for the regional offset of the SharePoint site
- We could also change the date field to only record the date, and it should default the dates to the regional first second of the day of the effected SharePoint site, in the case of App Testing 11/2/2021 12:00 AM (Mountain Time).
- Potentially it might be better to set the region to UTC

Let me know what you think?

**Comment by cgaine** [comment]
Hi Garrick,

We don't need the time.  Job date is a date only with no time.  Viktor was able to solve the issue on the integration side by removing the time.

**Comment by GarrickConvverge** [comment]
That works, but changing the Datetime column specifically to date without time on the SharePoint backend actually still creates a full date time entry in the SharePoint list of the form 11/2/2021 12:00 AM (Mountain Time) which would be stored as 11/2/2021 7:00 AM UTC  time so it should be able to cut off the time when loading it back in to sql and the report should also just automatically pull in the correct date.

I'll update that field to date.

**Comment by GarrickConvverge** [comment]
I have changed the field to be in test to be Date only, and tested by switching my time zone the date should now only be concerned with date time, but as I said its a little quirk in SharePoint where even though you select "Date" it stores a datetime set to the first second of the selected region a SharePoint site is set to. 

If you want we could make it a text column and that way we could remove the time altogether

**Comment by vikmol** [comment]
As I understand, you changed just formatting/representation of the field, not the field type. 
We need to be careful with field types as its change might require changing of sync task logic too.

As for a JobDate field itself, I would say that we do not care what exact time it is stored with as long as date will be the same regardless time zone it is viewed in. I believe we noticed the issue when JobDate had a time set after 6:00pm in local time. In this case (e.g. 2021-11-03 09:00pm MT time zone) when property was viewed in MT - it was 2021-11-03, but the same property in UTC would show up as 2021-11-04.

My approach for automation was just to cut off any time from JobDate and store it as YYYY-MM-DD 00:00:00 am (basically, I believe, time there can be anything up to 04:00:00pm and it would be the same date anywhere from UTC zone to Vancouver).
It is still DateTime type.  However, whenever we handle it in UTC or in any Canada wide timezone, the date will be the same.

I am conscious that this is not a proper solution, but just a workaround that we can use because we are not concerned in this particular case about time, only date is important. 

So, if you can store it always as, let's say, 11/2/2021 12:00 AM (Mountain Time) - it would suffice, I think.

**Comment by GarrickConvverge** [comment]
Sound good, we will just leave the field type to date and set it to Date only in the Pay Entry list settings. I can change this on test but I cannot on prod.

**Comment by vikmol** [comment]
I just tested in Test and pay entries were pushed successfully to VP_PayEntry list with JobDate there set to 'Date Only' Date and Time Format. 
I will change it in Prod along with deployment of OVPP updated version.
