### ISSUE TITLE
Add Permissions To App

### ISSUE THREAD

**Issue by GarrickConvverge** [Sanjel-Energy-Services/VariablePay_WorkItems#7]
Pay Entry 
    - Working District Managers can approve
Pay Statements 
    - Home District Managers can approve
Pay Period Summary 
    - Manager, Approval
    - Pay Roll Admin, Export

**Comment by GarrickConvverge** [comment]
-Add column to VP_Approvers - Roll

**Comment by GarrickConvverge** [comment]
There are threes roles implemented via the VP_Approvers list. 

- Managers can approve their respective districts
- Payroll Admins can export and close approved pay period summaries
- Admins can do everything

**Comment by cgaine** [comment]
Does the Admin role need a Service Point assigned?  -- never mind, it works for me now
