### ISSUE TITLE
Name field not populating when Edit Pay Entries

### ISSUE THREAD

**Issue by cgaine** [Sanjel-Energy-Services/VariablePay_WorkItems#9]
I've had it happen a few times, when you edit a pay entry the Employee name does not populate.

An example is GP job 464461, employee Jorge, when you edit those entries his name does not populate 

![image](https://user-images.githubusercontent.com/10456426/114466748-1e4a6300-9ba6-11eb-8b27-fda6d480d755.png)

**Comment by GarrickConvverge** [comment]
This looks to be an import Issue, Jorge doesn't seem to be on the Common_Employees List.

**Comment by vikmol** [comment]
Jorge was re-hired recently (starting April 12, 2021). His record is still not activated in ADP while he is appearing already on a job. 
I believe it is a pretty common case as ADP records might be not updated timely. 
As Jorge is a re-hire,  he had already Employee Number and Id assigned in eService database (inactive currently). So, he was associated with a Pay Entry initially. It can be worse with a new employee when there is no any records in ADP / eService by the time he  is at work. I do not see a way to deal with such cases without improving ADP entries timing.

On a general note, Common_Employees now have only active records. Thinking about that, it looks that we need to update it adding records deactivated, let's say, within at least the last month (to be sure that any delayed processing will not miss a recently terminated employee).

**Comment by cgaine** [comment]
Agreed

**Comment by vikmol** [comment]
Employees terminated within the last 31 day have been added to the Common_Employees list.
